doctrine:
    dbal:
        connections:
            db57:
                url: '%env(resolve:DB57_URL)%'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
            db80:
                url: '%env(resolve:DB80_URL)%'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
        default_connection: db57
    orm:
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                JSON_FILTER: App\Doctrine\Extension\Query\Mysql\JsonFilter
        hydrators:
            Translatable: App\Doctrine\Hydration\TranslatableHydrator
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
