doctrine_migrations:
    connection: db57
#    em: default <= disable connection and activate em when you want to do a doctrine:migrations:diff
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: false
